### ISSUE TITLE
Publish to Maven Central Repository?

### ISSUE THREAD

**Issue by lawrencehlee** [paulschwarz/spring-dotenv#1]
Hi Paul,

I love the library, and I'm trying to integrate it with a Spring application at work. However, Github requires an access token to install packages, and in the context of my employer, which doesn't currently use GitHub, that would require some bureaucratic movement (setting up accounts for individuals, for CI server, etc). 

Is it possible to publish this package to the Maven Central Repository? I realize I'm basically asking you to do additional work so that I don't have to, so it's understandable if you think it's not worth the effort. But maybe this is also a blocker for other folks who are looking to use this package.

Thanks!

**Comment by paulschwarz** [comment]
@lawrencehlee please see https://github.com/paulschwarz/spring-dotenv/releases and https://bintray.com/paulschwarz/maven/spring-dotenv and let me know if you have any suggestions or improvements.

**Comment by lawrencehlee** [comment]
Yep, that works - thanks!

**Comment by paulschwarz** [comment]
You're welcome. Would you mind letting me know if there were any steps you needed to set up the dependency? Did you have to add a repository to your pom/gradle?

**Comment by lawrencehlee** [comment]
I just added the repository to the pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    ...
    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-paulschwarz-maven</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/paulschwarz/maven</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>me.paulschwarz</groupId>
            <artifactId>spring-dotenv</artifactId>
            <version>1.0.0</version>
            <type>pom</type>
        </dependency>
    </dependencies>
</project>
```

**Comment by paulschwarz** [comment]
@lawrencehlee https://mvnrepository.com/artifact/me.paulschwarz/spring-dotenv
