### ISSUE TITLE
CVE in SpringFramework

### ISSUE THREAD

**Issue by juliusdev** [paulschwarz/spring-dotenv#10]
Hi,

Here, I'm afraid by this report :
https://mvnrepository.com/artifact/me.paulschwarz/spring-dotenv/2.5.1

Somes criticals CVE has been detected in the spring framework and fixed in the latest version.
Please can you update the project dependencies and release it ?

Cheers,
Julien

**Comment by paulschwarz** [comment]
I've pushed a version upgrade. Please review. Waiting for the release to by synced to the central repository.

**Comment by paulschwarz** [comment]
It seems the vulnerability report has not changed despite upgrading Spring Framework to the latest version. Any ideas? https://mvnrepository.com/artifact/me.paulschwarz/spring-dotenv/2.5.2

**Comment by paulschwarz** [comment]
I released 2.5.3 which is available from mavenCentral already, but it takes a while to be reflected in the Maven Repository unfortunately (sometimes a day).

Please check and confirm.

**Comment by paulschwarz** [comment]
Please upgrade to the latest

https://mvnrepository.com/artifact/me.paulschwarz/spring-dotenv/2.5.3
