### ISSUE TITLE
Vulnerabilities from dependencies

### ISSUE THREAD

**Issue by mbuechner** [paulschwarz/spring-dotenv#11]
See https://mvnrepository.com/artifact/me.paulschwarz/spring-dotenv/2.5.2

**Comment by paulschwarz** [comment]
Looking into this today

**Comment by paulschwarz** [comment]
Closing in favour of https://github.com/paulschwarz/spring-dotenv/issues/11

**Comment by paulschwarz** [comment]
Please upgrade to the latest

https://mvnrepository.com/artifact/me.paulschwarz/spring-dotenv/2.5.3
