### ISSUE TITLE
Issues with running building app

### ISSUE THREAD

**Issue by AnimeAllstar** [paulschwarz/spring-dotenv#19]
`spring-dotenv` works when I run my spring app on localhost but when I build it with `./mvnw clean package -DskipTests` and run try to run the JAR, I get this issue:
```
java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, ${env.DB_DATABASE}
```
Is there a way for me to use use values in the `.env` file while building a JAR?

**Comment by durimkryeziu** [comment]
Hi @AnimeAllstar, if you've upgraded the library version then try removing the `env.` prefix from your `application.yml/properties` file.
