### ISSUE TITLE
Spring Boot unable to read values for datasource

### ISSUE THREAD

**Issue by x80486** [paulschwarz/spring-dotenv#30]
## Description

I have a simple Spring Boot (3.2.2) application. I want to start using `spring-dotenv` for local development, so I started configuring the datasource to use environment variables instead, but somehow the application is not able to pick up the values from the `.env` file.

```groovy
developmentOnly("me.paulschwarz:spring-dotenv:4.0.0")
```

> I imported `spring-dotenv` in Gradle using `developmentOnly` but I've also tried `implementation`.

```yaml
# application.yaml
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
```

```properties
#
# File must be at the project's root

SPRING_DATASOURCE_PASSWORD = "bar"
SPRING_DATASOURCE_URL = "jdbc:oracle:thin:@tcp://database-hostname:1521/service-name"
SPRING_DATASOURCE_USERNAME = "foo"
```

## Environment

```shell
$ ./gradlew --version 

------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.2 (Eclipse Adoptium 21.0.2+13-LTS)
OS:           Linux 6.6.11-2-lts amd64
```

**Comment by x80486** [comment]
I just tried declaring the environment variables within the operating system (read: `export VAR="value"`) and the application worked fine — so I'm certain it's an issue with the library.

Somehow, when I start the application with Gradle using `./gradlew bootRun` it doesn't read them from `.env`.

**Comment by marchrius** [comment]
Hi, same issue here. The problem is not about SPRING_ prefixed environment variable but about the relaxed binding as described in #16

**Comment by x80486** [comment]
Looks like this is not going anywhere. For my use case, I just created a `.env` file at the project's root, and placed this block in `application.yaml`:

```yaml
spring:
  ...
  config:
    import: optional:file:.env[.properties]
  ...
```

I can read the file as usual, and while environment variables won't work, Spring properties will, so instead of writing, for instance, `DATASOURCE_PASSWORD` and try to read as an environment variable, I just write `spring.datasource.password` and get the same results.
